django_tutorials/locallibraray/locallibrary/catalog/urls.py
from django.urls import path
from catalog import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    # pk; primary key
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('booksloaned/', views.AllLoanedBooks.as_view(), name='all-borrowed'),
    # we changed the primary key id attribute for books model to a uuid hence why it is not int:pk
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),

]

django_tutorials/locallibraray/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    # redirects the base/root url to catalog
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
# from django.conf import settings
# from django.conf.urls.static import static
#
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_tutorials/locallibraray/locallibrary/catalog/models.py
from django.db import models
# Used to generate URLs by reversing the URL patterns
from django.urls import reverse
from django.contrib.auth.models import User

# Required unique book instances
import uuid
from datetime import date


class Language(models.Model):
    ''' Model representing a language.'''
    name = models.CharField(max_length=200,
                            help_text='Language the book is written in.')

    def __str__(self):
        return self.name


class Author(models.Model):
    '''Model representing an author.'''
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField('Born', null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
        permissions = (("can_crud_author", "Can create, update and delete Author objects"),)

    def get_absolute_url(self):
        '''Returns the url to access a particular author instance.'''
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        '''String for representing the Model object.'''
        return f'{self.last_name}, {self.first_name}'


class Genre(models.Model):
    '''Model representing a book genre.'''
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        '''String for representing the Model object.'''
        return self.name


class Book(models.Model):
    '''Model representing a book (but not a specific copy of a book).'''
    title = models.CharField(max_length=200)
    # Foreign Key used because book can only have one author,
    # but authors can have multiple books
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000,
                               help_text='''Enter a brief description of
                               the book''')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='''13 Character<a href='https://www.
                            isbn-international.org/content/what-isbn'>ISBN
                             number</a>''')
    # ManyToManyField used because genre can contain many books
    # and books can cover many genres.
    genre = models.ManyToManyField(Genre,
                                   help_text='Select a genre for this book')

    language = models.ManyToManyField(Language, help_text='Language of book')

    class Meta:
        permissions = (("can_crud_book", "Can create, update and delete Book objects"),)

    def __str__(self):
        '''String for representing the Model object.'''
        return self.title

    def get_absolute_url(self):
        '''Returns the url to access a detail record for this book.'''
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        '''Create a string for the Genre. This is required to display
           genre in Admin.'''
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    '''Model representing a specific copy of a book (i.e. that can be
       borrowed from the library).'''
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='''Unique ID for this particular
                          book across whole library''')
    # Can only be one book but many instances
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    # allows users to borrow book
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),
                       ("can_view_all_books", "View all books"),
                       )

    def __str__(self):
        '''String for representing the Model object.'''
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

django_tutorials/locallibraray/locallibrary/catalog/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        ''' Validates form data before submission.'''
        # Get our data after being cleaned by default validators.
        data = self.cleaned_data['renewal_date']
        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))
        # Remember to always return the cleaned data.
        return data


# ModelForm version of the above
# modelforms are great if you have a LOT of fields
class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        # fields = '__all__' to alter all fields
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _(
            'Enter a date between now and 4 weeks (default 3).')}

django_tutorials/locallibraray/locallibrary/catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Book, Author, BookInstance, Genre
from .forms import RenewBookForm

import datetime


def index(request):
    '''View function for home page of site.'''
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()
    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    # The number of fantasy genre books
    num_fantasy = Genre.objects.filter(name__icontains='fantasy').count()
    # number of books taht use the word fable
    num_fables = Book.objects.filter(summary__icontains='fable').count()
    # number of times a user has visited the website
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_fantasy': num_fantasy,
        'num_fables': num_fables,
        'num_visits': num_visits,
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    template_name = 'book_list.html'
    # restrict the number of listed items to 10/page.
    # placing /?page=2 at teh end of the link allows
    # you to see the next 10.
    paginate_by = 10

    # def get_context_data(self, **kwargs):
    #     # Call the base implementation first to get the context
    #     context = super(BookListView, self).get_context_data(**kwargs)
    #     # Create any data and add it to the context
    #     context['some_data'] = 'This is just some data'
    #     return context

    # your own name for the list as a template variable
    context_object_name = 'my_book_list'


# DetailView expects to be parsed a primary key (pk)
class BookDetailView(generic.DetailView):
    # context object name becomes the model name in lowercase
    model = Book
    template_name = 'book_detail.html'


# this MixIn will not let you access the page unless logged in
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    ''' CBV listing books on loan to current user.'''
    model = BookInstance
    template_name = 'bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        book_instances = BookInstance.objects.filter(
            borrower=self.request.user)
        return book_instances.filter(status__exact='o').order_by('due_back')


class AllLoanedBooks(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'bookinstance_list.html'
    paginate_by = 10
    permission_required = 'catalog.can_view_all_books'


class AuthorListView(generic.ListView):
    model = Author
    template_name = 'author_list.html'
    paginate_by = 10
    context_object_name = 'my_author_list'


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'


# Functional View for our RenewBookForm
@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    ''' Gives librarians the ability to renew loaned books.
    Args:
        pk (uuid): primary key of a BookInstance
    '''
    book_instance = get_object_or_404(BookInstance, pk=pk)
    # If this is a POST request then process the Form data
    if request.method == 'POST':
        # Create a form instance and populate it with data
        # from the request (binding):
        book_renewal_form = RenewBookForm(request.POST)
        # Check if the form is valid:
        if book_renewal_form.is_valid():
            # process the data in form.cleaned_data as required
            # (here we just write it to the model due_back field)
            book_instance.due_back = book_renewal_form.cleaned_data['renewal_date']
            book_instance.save()
            # redirect to a new URL:
            # reverse generates the URL used in the URLConfig name
            return HttpResponseRedirect(reverse('all-borrowed'))
    # If this is a GET (or any other method)
    # create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        # RenewBookForm.renewal_date = proposed_renewal_date
        book_renewal_form = RenewBookForm(
            initial={'renewal_date': proposed_renewal_date})
    context = {
            'form': book_renewal_form,
            'book_instance': book_instance,
    }
    return render(request, 'book_renew_librarian.html', context)


# Generic form views that handle BOTH the view and form creation
class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}
    template_name = 'generic_form.html'
    # template name is always {app_name}/{model}_form.html
    # e.g. catalog/author_form.html
    permission_required = 'catalog.can_crud_author'


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    template_name = 'generic_form.html'
    permission_required = 'catalog.can_crud_author'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    # a redirection url after deletion
    success_url = reverse_lazy('authors')
    template_name = 'confirm_delete.html'
    # template name is always {app_name}/{model}_confirm_delete.html
    permission_required = 'catalog.can_crud_author'

    def get_context_data(self, **kwargs):
        ''' Passes model name to the context.'''
        context = super().get_context_data(**kwargs)
        context['model_name'] = 'Author'
        return context


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    # initial = {'date_of_death': '05/01/2018'}
    template_name = 'generic_form.html'
    permission_required = 'catalog.can_crud_book'


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    template_name = 'generic_form.html'
    permission_required = 'catalog.can_crud_book'


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    # a redirection url after deletion
    success_url = reverse_lazy('books')
    template_name = 'confirm_delete.html'
    permission_required = 'catalog.can_crud_book'

    def get_context_data(self, **kwargs):
        ''' Passes model name to the context.'''
        context = super().get_context_data(**kwargs)
        context['model_name'] = 'Book'
        return context

django_tutorials/locallibraray/locallibrary/catalog/templates/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author: {{ author }}</h1>
<p>{{ author.date_of_birth }} - {{ author.date_of_death }}</p> 

<div style='margin-left:20px;margin-top:20px'>
  <h4>Books</h4>
  {% for book in author.book_set.all %}
    <hr>
	<p><a href="{% url 'book-detail' book.pk %}">{{book.title}}</a> ({{book.pk}})</p>
	<p>{{ book.summary }}</p>
  {% endfor %}
  
{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/author_list.html
{% extends "base_generic.html" %}

{# loops through all authors and gives a link for the author and the uthor name #}
{% block content %}
  <h1>Author List</h1>
  {% if my_author_list %}
  <ul>
    {% for author in my_author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author }}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in the library.</p>
  {% endif %}       
{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/base_generic.html
<!DOCTYPE html>
<!-- This is a base template for all pages, consists of a side panel navigation bar with links to all areas of the site --!>
<html lang="en">
<head>
  {% block title %}
    <title>Local Library</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- link to an external css stylesheet --!>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      <!-- django template for the navigation page that will be used on every other page --!>
      {% block sidebar %}
        <ul class="sidebar-nav">
           {# optional login page #}
		   <hr>
		   {% if user.is_authenticated %}
			 <li>User: {{ user.get_username }}</li>
			 <li><a href="{% url 'my-borrowed' %}">My Books</a></li>
			 <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
		   {% else %}
			 <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
		   {% endif %} 
		   {% if perms.catalog.can_mark_returned %}
             <hr>
             <li>Manage</li>
		     <li><a href="{% url 'all-borrowed' %}">All Borrowed</a></li>
           {% endif %}
		  <hr>
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
		  <li><a href="{% url 'authors' %}">All authors</a></li>
		</ul>
     {% endblock %}
      </div>
      <!-- The below "block content" will be replaced by the block content in the child template file --!>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
     {% block pagination %}
       {% if is_paginated %}
         <div class="pagination">
           <span class="page-links">
             {% if page_obj.has_previous %}
               <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
             {% endif %}
             <span class="page-current">
               <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
             </span>
             {% if page_obj.has_next %}
               <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
             {% endif %}
           </span>
         </div>
       {% endif %}
     {% endblock %} 
    </div>
  </div>
</body>
</html>

django_tutorials/locallibraray/locallibrary/catalog/templates/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>
  <!-- author detail link not yet defined -->
  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> 
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {% for lang in book.language.all %} {{ lang }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>
    {% if book.bookinstance_set.all %}
      {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
        {% if copy.status != 'a' %}
          <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{copy.imprint}}</p>
        <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
      {% endfor %}
	{% else %}
	  <p>No book instances exist.</p>
	{% endif %}
  </div>
{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/book_list.html
{% extends "base_generic.html" %}

{# loops through all books and gives a link for the book and the uthor name #}
{% block content %}
  <h1>Book List</h1>
  {% if my_book_list %}
  <ul>
    {% for book in my_book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
      
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_table }}
      <input type="submit" value="Submit">
    </form>
{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/bookinstance_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>
	{% if perms.catalog.can_view_all_books %}
      {% if bookinstance_list %}
      <ul>

        {% for bookinst in bookinstance_list %} 
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
          ({{ bookinst.due_back }})        
	      {% if perms.catalog.can_mark_returned %}
             - <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  
          {% endif %}
        </li>
        {% endfor %}
      </ul>

      {% else %}
        <p>There are no books borrowed.</p>
      {% endif %}       
	{% else %}
	  <p> You do not have permission to view this page.</p>
	{% endif %}
{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a> 
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete {{ model_name }}</h1>
{# object keyword is the parsed model.__str__ #}
<p>Are you sure you want to {{ model_name }} the {{ model_name }}: {{ object }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/generic_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

django_tutorials/locallibraray/locallibrary/catalog/templates/index.html
<!-- use base_generic as the base html --!>
{% extends "base_generic.html" %}

<!-- override the existing block title in base_template --!>
{% block title %}<b>Local Library Home</b>{% endblock %}
<!-- replace the "block content" in the base html with the below code --!>
{% block content %}
<h1>The Local Library</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Fantasy:</strong> {{ num_fantasy }}</li>
    <li><strong>Fables in synopsis:</strong> {{ num_fables }}</li>
  </ul>
<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}